// GENERATED by tools/sync-test-data.mjs from test-data/*.json. Do not edit: change the JSON, then run
// `npm run sync:test-data` (the runner also does it before every run).
output.data = {
  "contract": {
    "app": {
      "androidPackage": "com.faiz.streak",
      "localBuildPackage": "com.faiz.streak.local",
      "iosBundleId": "com.faiz.streak"
    },
    "screens": {
      "welcome": "onboarding-step-0",
      "intensity": "onboarding-step-1",
      "setup": "onboarding-step-2",
      "loginNew": "login-new",
      "loginExisting": "login-existing",
      "home": "home-screen",
      "insights": "insights-screen",
      "history": "history-screen",
      "profile": "profile-screen",
      "heatmap": "calendar-screen",
      "settingsAccount": "settings-account",
      "settingsAppearance": "settings-appearance",
      "settingsNotifications": "settings-notifications",
      "settingsActivities": "settings-activities",
      "settingsPrivacy": "settings-privacy",
      "settingsAbout": "settings-about"
    },
    "ids": {
      "onboarding": {
        "primary": "onboarding-primary",
        "skip": "onboarding-skip",
        "haveAccount": "onboarding-have-account",
        "heroHeatmap": "holdable-heatmap",
        "activity": "activity-{activity}",
        "reminderRow": "reminder-row",
        "reminderToggle": "reminder-row-toggle"
      },
      "login": {
        "skip": "login-skip",
        "logo": "logo-mark",
        "continueEmail": "login-continue-email",
        "emailInput": "login-email-input",
        "sendCode": "login-send-code",
        "otpInput": "otp-input",
        "resend": "login-resend",
        "differentEmail": "login-different-email",
        "banner": "login-banner"
      },
      "tabs": {
        "home": "tab-home",
        "insights": "tab-insights",
        "history": "tab-history",
        "profile": "tab-profile",
        "fab": "fab-check-in",
        "indicator": "tab-indicator"
      },
      "home": {
        "streak": "home-streak",
        "activeDays": "home-active-days",
        "thisWeek": "home-this-week",
        "trend": "home-trend",
        "trendDay": "home-trend-D",
        "trendWeek": "home-trend-W",
        "trendMonth": "home-trend-M",
        "month": "month-{year}-{month0}"
      },
      "heatmap": {
        "viewYear": "calendar-view-year",
        "viewMonth": "calendar-view-month",
        "title": "calendar-title",
        "yearTotal": "calendar-year-total",
        "month": "month-{year}-{month0}",
        "dayTile": "tile-{iso}"
      },
      "sheets": {
        "close": "sheet-close",
        "checkIn": "check-in-sheet",
        "checkInActivity": "activity-{activity}",
        "checkInPreview": "check-in-preview",
        "checkInSave": "check-in-save",
        "day": "day-sheet",
        "dayCount": "day-count",
        "dayAdd": "day-add",
        "dayPicker": "day-picker",
        "dayPickerOpen": "day-picker-open"
      },
      "profile": {
        "checkIns": "profile-check-ins",
        "account": "profile-account",
        "appearance": "profile-appearance",
        "notifications": "profile-notifications",
        "activities": "profile-activities",
        "privacy": "profile-privacy",
        "logOut": "profile-log-out"
      },
      "androidDialog": {
        "confirm": "android:id/button1",
        "cancel": "android:id/button2",
        "message": "android:id/message"
      }
    },
    "labels": {
      "navBack": "Back",
      "onboarding": {
        "welcomeTitle": "See your consistency at a glance",
        "intensityLevels": [
          "No activity",
          "Light",
          "Moderate",
          "Strong",
          "Peak"
        ],
        "setupTitle": "What will you track\\?",
        "reminder": "Daily reminder at 8:00 PM",
        "step": "Step {n} of 3",
        "getStarted": "Get started",
        "continue": "Continue",
        "startTracking": "Start tracking"
      },
      "login": {
        "newTitle": "Create your Streak account",
        "existingTitle": "Welcome back",
        "google": "Continue with Google",
        "googleBusy": "Connecting…",
        "emailTitle": "Continue with email",
        "codeTitle": "Check your inbox",
        "codeSubtitle": "Enter the code sent to {email}",
        "sending": "Sending…",
        "verifying": "Verifying…",
        "resendCooldown": "Resend code \\(.+\\)",
        "invalidCode": "That code is wrong or has expired.*",
        "terms": "Terms",
        "privacy": "Privacy Policy"
      },
      "home": {
        "title": "Your activity",
        "profileAvatar": "Profile",
        "heatmapHeader": "\\d{4}, .+ check-ins?",
        "emptyHeatmap": "Your heatmap starts today",
        "firstCheckIn": "Log your first check-in",
        "previousMonths": "Previous months",
        "nextMonths": "Next months",
        "seeAll": "See all"
      },
      "heatmap": {
        "title": "Heatmap",
        "previousYear": "Previous year",
        "nextYear": "Next year",
        "previousMonth": "Previous month",
        "nextMonth": "Next month",
        "intensityCard": "How intensity works"
      },
      "profile": {
        "guestName": "Guest",
        "editProfile": "Edit profile",
        "exportData": "Export data",
        "about": "About Streak"
      },
      "dialogs": {
        "logOutTitle": "Log out\\?"
      }
    }
  },
  "accounts": {
    "google": {
      "emailEnv": "GOOGLE_TEST_ACCOUNT",
      "auth": "interactive",
      "notes": [
        "The account's address is private: set it in .env (GOOGLE_TEST_ACCOUNT), never in a committed file.",
        "Automation never stores or types the Google password and never bypasses Google's checks.",
        "Add the account to the test phone once (Settings > Accounts > Add account > Google).",
        "The flow taps Google's account chooser entry for this address (GOOGLE_AUTO_PICK=true) and then waits",
        "up to HUMAN_TIMEOUT_MS for a person to finish anything Google asks (consent, password, 2-step)."
      ]
    },
    "emailOtp": {
      "emailEnv": "TEST_USER_EMAIL",
      "auth": "email one-time code (Streak has no passwords)",
      "codeSource": "Supabase Auth admin API generate_link, called by the runner's local OTP broker",
      "secretsEnv": [
        "SUPABASE_URL",
        "SUPABASE_SERVICE_ROLE_KEY"
      ],
      "notes": [
        "Use a dedicated dummy address you control (e.g. streak.e2e+01@yourdomain.test that forwards to you).",
        "The service_role key stays inside the runner process: Maestro only gets a one-run localhost URL."
      ]
    },
    "guest": {
      "auth": "none",
      "notes": [
        "Skip on Welcome or on the Login screen; check-ins stay on the device."
      ]
    }
  },
  "inputs": {
    "email": {
      "invalid": [
        "not-an-email",
        "person@",
        "person@example"
      ],
      "valid": "person@example.com",
      "validWithCaps": "Person@Example.COM"
    },
    "otp": {
      "wrong": "000000",
      "incomplete": "12345"
    },
    "onboarding": {
      "activities": [
        "workout",
        "deep-work",
        "reading",
        "meditate",
        "walk",
        "water"
      ],
      "selectedByDefault": [
        "workout",
        "deep-work",
        "reading"
      ],
      "pick": "walk"
    },
    "checkIn": {
      "activity": "workout"
    }
  },
  "audit": {
    "home": {
      "screen": "home-screen",
      "elements": [
        {
          "name": "Profile avatar",
          "text": "Profile",
          "expect": "profile-screen",
          "back": "tab:home"
        },
        {
          "name": "Heatmap year title",
          "text": "\\d{4}, .+ check-ins?",
          "expect": "calendar-screen",
          "back": "nav"
        },
        {
          "name": "Current month on the heatmap",
          "id": "month-{year}-{month0}",
          "expect": "day-picker",
          "back": "sheet"
        },
        {
          "name": "Log your first check-in",
          "text": "Log your first check-in",
          "expect": "check-in-sheet",
          "back": "sheet"
        },
        {
          "name": "See all",
          "text": "See all",
          "expect": "history-screen",
          "back": "tab:home"
        },
        {
          "name": "New check-in (+)",
          "id": "fab-check-in",
          "expect": "check-in-sheet",
          "back": "system"
        }
      ]
    },
    "profile": {
      "screen": "profile-screen",
      "elements": [
        {
          "name": "Edit profile (pencil)",
          "text": "Edit profile",
          "expect": "settings-account",
          "back": "nav"
        },
        {
          "name": "Account settings",
          "id": "profile-account",
          "expect": "settings-account",
          "back": "system"
        },
        {
          "name": "Appearance",
          "id": "profile-appearance",
          "expect": "settings-appearance",
          "back": "nav"
        },
        {
          "name": "Notifications",
          "id": "profile-notifications",
          "expect": "settings-notifications",
          "back": "system"
        },
        {
          "name": "Activity preferences",
          "id": "profile-activities",
          "expect": "settings-activities",
          "back": "nav"
        },
        {
          "name": "Data & privacy",
          "id": "profile-privacy",
          "expect": "settings-privacy",
          "back": "system"
        },
        {
          "name": "Export data",
          "text": "Export data.*",
          "expect": "settings-privacy",
          "back": "nav"
        },
        {
          "name": "About Streak",
          "text": "About Streak",
          "expect": "settings-about",
          "back": "nav"
        }
      ]
    },
    "heatmap": {
      "screen": "calendar-screen",
      "elements": [
        {
          "name": "Month view segment",
          "id": "calendar-view-month",
          "expect": "tile-{iso}",
          "back": "none"
        },
        {
          "name": "Today's day tile",
          "id": "tile-{iso}",
          "expect": "day-sheet",
          "back": "sheet"
        },
        {
          "name": "Year view segment",
          "id": "calendar-view-year",
          "expect": "month-{year}-{month0}",
          "back": "none"
        },
        {
          "name": "Current month in the year",
          "id": "month-{year}-{month0}",
          "expect": "day-picker",
          "back": "system"
        },
        {
          "name": "Back to Home",
          "text": "Back",
          "expect": "home-screen",
          "back": "none"
        }
      ]
    }
  }
}
